# Generated by Django 5.1.1 on 2024-10-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_created_at_alter_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_names',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
    ]
