# Generated by Django 5.1.1 on 2024-09-29 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macbook', '0002_macbook_macbook_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='macbook',
            old_name='macbook_dec',
            new_name='dec',
        ),
        migrations.RenameField(
            model_name='macbook',
            old_name='macbook_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='macbook',
            old_name='macbook_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='macbook',
            old_name='macbook_price',
            new_name='price',
        ),
    ]
