# Generated by Django 5.1.1 on 2024-09-30 18:59

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macbook', '0004_macbook_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macbook',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='macbook',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from=models.TextField(), unique=True),
        ),
    ]
