server {
    listen 80 default_server;
    server_name _;

    # Disable logging for favicon.ico
    location = /favicon.ico { 
        access_log off; 
        log_not_found off; 
    }

    # Serve static files
    location /static/ {
        alias /home/ubuntu/OneStopSolutions/static/;  # Updated to match your 'static' folder
        autoindex off;
    }

    # Proxy pass to Gunicorn
    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }
}
