# Generated by Django 5.1.1 on 2024-10-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product_slug',
            field=models.SlugField(default=''),
        ),
    ]
