# Generated by Django 5.1.1 on 2024-09-29 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipad', '0002_ipad_ipad_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipad',
            old_name='ipad_dec',
            new_name='dec',
        ),
        migrations.RenameField(
            model_name='ipad',
            old_name='ipad_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='ipad',
            old_name='ipad_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ipad',
            old_name='ipad_price',
            new_name='price',
        ),
    ]
