# Generated by Django 5.1.1 on 2024-09-29 06:40

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipad', '0003_rename_ipad_dec_ipad_dec_rename_ipad_img_ipad_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipad',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from=models.CharField(max_length=50), unique=True),
        ),
    ]
