# Generated by Django 5.1.1 on 2024-10-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipad', '0006_alter_ipad_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipad',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
