# Generated by Django 5.1.1 on 2024-09-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='laptop_price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
