# Generated by Django 5.1.1 on 2024-09-29 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0002_laptop_laptop_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='laptop_dec',
            new_name='dec',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='laptop_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='laptop_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='laptop_price',
            new_name='price',
        ),
    ]
