# Generated by Django 5.1.1 on 2024-10-01 13:39

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0005_alter_laptop_name_alter_laptop_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
