# Generated by Django 5.1.1 on 2024-09-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iphone_img', models.FileField(default=None, max_length=250, null=True, upload_to='iphones/')),
                ('iphone_name', models.CharField(max_length=50)),
                ('iphone_dec', models.TextField()),
            ],
        ),
    ]
