# Generated by Django 5.1.1 on 2024-09-29 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iphone', '0002_iphone_iphone_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iphone',
            old_name='iphone_dec',
            new_name='dec',
        ),
        migrations.RenameField(
            model_name='iphone',
            old_name='iphone_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='iphone',
            old_name='iphone_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='iphone',
            old_name='iphone_price',
            new_name='price',
        ),
    ]
