# Generated by Django 5.1.1 on 2024-09-29 06:09

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iphone', '0003_rename_iphone_dec_iphone_dec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iphone',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from=models.CharField(max_length=50), unique=True),
        ),
    ]
