# Generated by Django 5.1.1 on 2024-10-01 13:39

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iphone', '0005_alter_iphone_name_alter_iphone_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iphone',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
